[2024-07-24 07:28:14,832] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:29:33,824] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/v1/login HTTP/1.1" 200 10146
[2024-07-24 07:29:50,368] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/v1/login HTTP/1.1" 200 10146
[2024-07-24 07:30:19,063] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 11, in post
    jwt = self._get_jwt(request)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 19, in _get_jwt
    return data.Authorization
AttributeError: 'dict' object has no attribute 'Authorization'
[2024-07-24 07:30:19,064] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 83240
[2024-07-24 07:31:06,258] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:31:06,493] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:31:33,998] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:31:34,241] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:31:42,510] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:31:42,786] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:31:50,682] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 14, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 19, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:31:50,683] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114401
[2024-07-24 07:32:10,339] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:32:10,569] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:32:13,760] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:32:13,982] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:32:18,614] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 19, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:32:18,615] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114420
[2024-07-24 07:32:40,533] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:32:40,758] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:32:45,974] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:32:46,208] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:32:49,755] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 20, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:32:49,757] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114477
[2024-07-24 07:33:13,769] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:33:14,011] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:33:22,700] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 20, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:33:22,701] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114489
[2024-07-24 07:33:38,497] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:33:38,731] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:33:47,983] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:33:48,219] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:33:52,634] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 19, in requestData
    print(json.dump(data))
TypeError: dump() missing 1 required positional argument: 'fp'
[2024-07-24 07:33:52,634] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 79240
[2024-07-24 07:34:18,786] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:34:18,999] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:34:24,104] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 18, in requestData
    print(json.dump(data))
TypeError: dump() missing 1 required positional argument: 'fp'
[2024-07-24 07:34:24,104] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 79270
[2024-07-24 07:34:34,399] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:34:34,681] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:34:37,889] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:34:38,116] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:34:49,870] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 20, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:34:49,871] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114460
[2024-07-24 07:35:09,708] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:35:09,982] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:35:16,056] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 20, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:35:16,057] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114452
[2024-07-24 07:35:34,464] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:35:34,685] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:35:39,462] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 20, in requestData
    return response.json()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:35:39,463] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114453
[2024-07-24 07:35:49,035] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:35:49,326] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:35:59,388] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 15, in post
    req = self.requestData(data, url, "")
  File "/opt/ygwuliu_logistics/api/core/request.py", line 19, in requestData
    print('=============>', response.json())
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:35:59,389] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 114745
[2024-07-24 07:36:43,206] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:36:43,448] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:37:00,790] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:37:01,008] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:37:03,196] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:37:03,449] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:37:09,039] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:37:09,040] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:37:42,110] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:37:42,356] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:39:19,758] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/constant.py changed, reloading.
[2024-07-24 07:39:19,979] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:39:28,232] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/constant.py changed, reloading.
[2024-07-24 07:39:28,454] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:39:36,275] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:39:36,275] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:40:34,463] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:40:34,721] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:40:35,718] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:40:35,718] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:41:51,886] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/ygwuliu_logistics/api/viewset/AuthViewset.py", line 12, in post
    data = json.loads(request.body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24 07:41:51,886] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 88883
[2024-07-24 07:42:06,598] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:42:06,599] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:42:50,533] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:42:50,768] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:42:55,705] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:42:55,706] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:43:20,341] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:43:20,565] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:43:25,097] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:43:25,098] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:43:42,209] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:43:42,209] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:43:58,202] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:43:58,448] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:46:00,158] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:46:00,401] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:46:21,791] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:46:22,010] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:46:35,483] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:46:35,483] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:46:56,633] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/constant.py changed, reloading.
[2024-07-24 07:46:56,865] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:46:59,023] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/constant.py changed, reloading.
[2024-07-24 07:46:59,246] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:47:04,793] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:47:04,793] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:47:30,890] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:47:31,125] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:47:35,462] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:47:35,463] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:47:49,733] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'Response' object has no attribute 'get'
[2024-07-24 07:47:49,733] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 65124
[2024-07-24 07:47:57,665] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:47:57,921] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:48:00,588] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 33, in process_response
    response.headers['X-Frame-Options'] = self.get_xframe_options_value(
AttributeError: 'dict' object has no attribute 'headers'
[2024-07-24 07:48:00,588] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 66565
[2024-07-24 07:48:29,503] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/core/request.py changed, reloading.
[2024-07-24 07:48:29,736] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:49:04,341] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:49:04,571] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:49:07,454] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/v1/login/
Traceback (most recent call last):
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/ygwuliu_logistics/venv/lib/python3.10/site-packages/rest_framework/response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
AssertionError: .accepted_renderer not set on Response
[2024-07-24 07:49:07,454] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/v1/login/ HTTP/1.1" 500 69622
[2024-07-24 07:49:56,419] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /opt/ygwuliu_logistics/api/viewset/AuthViewset.py changed, reloading.
[2024-07-24 07:49:56,638] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:50:35,637] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2024-07-24 07:50:39,329] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/v1/login/ HTTP/1.1" 200 798
